version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/my-memory
    overwrite: yes

permissions:
  - object: /home/ubuntu/my-memory
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: ubuntu
  
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ubuntu
  
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: ubuntu