spring:
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  application:
    name: memory-batch
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  token:
    enabled: false

cloud:
  aws:
    enabled: false

cors:
  enabled: false

---
spring:
  profiles:
    active: local
    include:
      - local-db
