server:
  port: 8080
  shutdown: graceful

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
      format_sql: true
      use_sql_comments: true
      default_batch_fetch_size: 1000
      jdbc:
          batch_size: 50
    open-in-view: false

jwt:
  token:
    expiration: 3600
    refresh: 2592000
    enabled: true

cloud:
  aws:
    enabled: true

cors:
  allowed-origins:
    - http://localhost:4173
    - http://localhost:5173
    - http://144.24.78.166
    - https://144.24.78.166
    - http://my-memory-front.s3-website.ap-northeast-2.amazonaws.com
    - https://my-memory-front.s3-website.ap-northeast-2.amazonaws.com
  enabled: true

---

spring:
  profiles:
    active: local
    include:
      - local-jwt
      - local-db
      - local-aws
      - swagger

---

spring:
  profiles:
    active: dev
    include:
      - dev-jwt
      - dev-db
      - dev-aws
      - swagger