spring:
  application:
    name: memory-api
  config:
      activate:
          on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/myMemory
    username: postgres
    password: 1111
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
        jdbc:
          batch_size: 50
    open-in-view: false

jwt:
  token:
    expiration: 3600
    refresh: 604800
    secret: secure_enough_for_the_HS256_algorithm_memory_secret_key_v1


