server:
  port: 8080
  shutdown: graceful

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
      validation-timeout: 5000
      max-lifetime: 1800000
  jpa:
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
      format_sql: true
      use_sql_comments: true
      default_batch_fetch_size: 1000
      jdbc:
          batch_size: 50
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: false
    table: flyway_schema_history
    baseline-version: 0
    baseline-description: "Initial baseline"
    clean-disabled: false

jwt:
  token:
    expiration: 3600
    refresh: 2592000
    enabled: true

cloud:
  aws:
    enabled: true

cors:
  allowed-origins:
    - "http://localhost:4173"
    - "http://localhost:5173"
    - "http://dev.mymemory.co.kr"
    - "https://dev.mymemory.co.kr"
    - "http://www.mymemory.co.kr"
    - "https://www.mymemory.co.kr"
    - "http://mymemory.co.kr"
    - "https://mymemory.co.kr"
  enabled: true

---

spring:
  profiles:
    active: local
    include:
      - local-jwt
      - local-db
      - local-aws
      - swagger
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false  # 로컬에서는 clean 허용
    validate-on-migrate: false
    baseline-version: 0
    baseline-description: "Initial baseline"

---

spring:
  profiles:
    active: dev
    include:
      - dev-jwt
      - dev-db
      - dev-aws
      - swagger
  flyway:
    enabled: true
    baseline-on-migrate: false
    clean-disabled: true  # 개발환경에서는 clean 비활성화
    validate-on-migrate: true
    baseline-version: 0
    baseline-description: "Initial baseline"

---

spring:
  profiles:
    active: prod
    include:
      - prod-jwt
      - prod-db
      - prod-aws
  flyway:
    enabled: true
    baseline-on-migrate: false  # 운영환경에서는 baseline 비활성화
    clean-disabled: true  # 운영환경에서는 clean 비활성화
    validate-on-migrate: true