server:
  port: 8080
  shutdown: graceful

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
      format_sql: true
      use_sql_comments: true
      default_batch_fetch_size: 1000
      jdbc:
          batch_size: 50
    open-in-view: false

jwt:
  token:
    expiration: 3600
    refresh: 2592000

---

spring:
  profiles:
    active: local
    include:
      - local-jwt
      - local-db
      - local-aws
      - swagger

---

spring:
  profiles:
    active: dev
    include:
      - dev-jwt
      - dev-db
      - dev-aws
      - swagger