### signup
POST {{memory_api}}/api/v1/member/signup
Content-Type: application/json

{
  "email": "tnswh2023@naver.com",
  "password": "1234",
  "name": "tnswh",
  "nickname": "tnswh",
  "profileImageUrl": "aa"
}

### login
POST {{memory_api}}/api/v1/member/login
Content-Type: application/json

{
  "email": "tnswh2023@naver.com",
  "password": "1234"
}

> {%
    client.global.set("access_token", response.body.data.accessToken);
%}

### find member (requires JWT token)
GET {{memory_api}}/api/v1/member/me
Authorization: Bearer {{access_token}}

### update member (requires JWT token)
PUT {{memory_api}}/api/v1/member/me
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "nickname": "Updated Nickname",
  "profileImageUrl": "https://new-profile-image-url.com/image.jpg"
}

### update password (requires JWT token)
PUT {{memory_api}}/api/v1/member/me/password
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "password": "newpassword"
}

### find member by email
GET {{memory_api}}/api/v1/member/email?email=tnswh2023@naver.com
