version: '3.8'

services:
  app:
    image: 228749872437.dkr.ecr.ap-northeast-2.amazonaws.com/my_memory/memory:latest
    container_name: my-memory
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 750M
        reservations:
          memory: 250M
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms250m -Xmx550m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:MaxMetaspaceSize=128m"
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      CLOUD_AWS_CREDENTIALS_ACCESS-KEY: ${AWS_S3_ACCESS_KEY}
      CLOUD_AWS_CREDENTIALS_SECRET-KEY: ${AWS_S3_SECRET_KEY}
      CLOUD_AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      CLOUD_AWS_REGION_STATIC: ${AWS_S3_REGION}
      CLOUD_AWS_S3_ENDPOINT: ${AWS_S3_ENDPOINT}
      JWT_TOKEN_SECRET: ${JWT_TOKEN_SECRET}
      SPRING_ELASTICSEARCH_URIS: ${ELASTIC_URIS}
      SPRING_ELASTICSEARCH_USERNAME: elastic
      SPRING_ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD}
    networks:
      - memory-network
    restart: always

networks:
  memory-network:
    driver: bridge

volumes:
  postgres-data:
