### Login first to get access token
POST {{memory_api}}/api/v1/member/login
Content-Type: application/json

{
  "email": "tnswh2023@naver.com",
  "password": "1234"
}

> {%
    client.global.set("access_token", response.body.data.accessToken);
%}

### Create a new image
POST {{memory_api}}/api/v1/file?fileType=MEMBER
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{access_token}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="memory_rogo.png"

< ./memory_rogo.png
--WebAppBoundary--

### Upload multiple images
POST {{memory_api}}/api/v1/files?fileType=MEMORY
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{access_token}}

--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="memory_rogo.png"

< ./memory_rogo.png
--WebAppBoundary
Content-Disposition: form-data; name="files"; filename="memory_rogo2.png"

< ./memory_rogo.png
--WebAppBoundary--
