name: Deploy to Development Server

on:
  workflow_run:
    workflows: ["Build and Push to GHCR"]
    types:
      - completed
    branches: [ develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Deploy to development server
      uses: appleboy/ssh-action@master
      with:
        host: 144.24.78.166
        username: ubuntu
        key: ${{ secrets.DEV_SERVER_PRIVATE_KEY }}
        script: |
          # GitHub Container Registry 로그인
          echo ${{ secrets.PAT_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # 프로젝트 디렉토리 생성 및 이동
          mkdir -p ~/memory/memory-backend
          cd ~/memory/memory-backend
          
          # 기존 저장소가 없다면 클론, 있다면 풀
          if [ ! -d ".git" ]; then
            git clone -b develop https://github.com/${{ github.repository }}.git .
          else
            git fetch origin develop
            git reset --hard origin/develop
          fi
          
          # docker compose 실행
          cd memory-infra/docker/dev
          
          # .env 파일 생성
          cat > .env << EOF
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          JWT_TOKEN_SECRET=${{ secrets.JWT_TOKEN_SECRET }}
          LETSENCRYPT_EMAIL=my.memory.world2025@gmail.com
          EOF
          
          # 기존 컨테이너 중지 및 제거
          docker compose down
          
          sleep 10
          
          # 기존 이미지 제거 (추가)
          docker compose pull
  
          # 컨테이너 빌드 및 시작
          docker compose up -d --build
          
          # 사용하지 않는 이미지 정리
          docker image prune -f